apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: business_command_and_control
  description: bian-business-area Businees Command and Control
spec:
  owner: API-Platform
  domain: business_support
